apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: cs3219
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer # to expose to the public, the type of this service should be LoadBalancer instead of ClusterIP (for internal comms)

