FROM nginx

# in the official nginx image, the location for the default config file is at /etc/nginx/conf.d/
# for other images, there are default directories that we may find this in, it's a documentation search away.
COPY default.conf /etc/nginx/conf.d/default.conf
