version: "3.9"
# these are the two services running in the container: a node application and an nginx reverse proxy
services: 
    nodeserver:
      build:
          context: ./app  # provides the directory context for this service file, the Dockerfile within it will do the rest
      ports:
          - "5000:5000" # first arg is localhost port, second arg is the container's port 
    nginx:
      restart: always
      build:
          context: ./nginx
      ports:
          - "80:80"


# =============== NOTES ===================
#1. Docker compose allows us to setup inter-service communications, allowing the two containers to talk to each other
#
#
