apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs
  name: nodejs
spec:
  containers:
  - command:
    - sh
    - ./wait.sh
    image: rest-app
    name: nodejs
    ports:
    - containerPort: 4000
    resources: {}
  restartPolicy: OnFailure
status: {}
