name: Test backend task b
on:
  push:
    paths:
      - "taskB/**"
    branches:
      - "**"
jobs:
  deploy:
    name: task b deploy
    strategy:
      matrix:
        node-version: [ 14.x ]
        mongodb-version: [ "5.0" ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v1
      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
#      - name: Install dependencies
#        run: npm install
      - name: Test Endpoints
        run: |
          echo "Checking current directory before running test :"
          pwd
          npm test
        env:
          CI: true
#      - name: Install zip
#        uses: montudor/action-zip@v1
#      - name: Zip
#        run: zip -qq -r ./nodejs.zip ./
#      - name: Push to lambda
#        uses: appleboy/lambda-action@master
#        with:
#          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
#          aws_region: ap-southeast-1
#          function_name: test
#          zip_file: ./app/nodejs.zip
